Repository gibum1228/Care_Refrigerator, pull requests merged in 2020-04, with the labels that each got.

#1 2020.04.14.
  Care_Refrigerator/.gitignore
  Care_Refrigerator/.idea/codeStyles/Project.xml
  Care_Refrigerator/.idea/gradle.xml
  Care_Refrigerator/.idea/kotlinCodeInsightSettings.xml
  Care_Refrigerator/.idea/misc.xml
  Care_Refrigerator/.idea/runConfigurations.xml
  Care_Refrigerator/app/.gitignore
  Care_Refrigerator/app/build.gradle
  Care_Refrigerator/app/proguard-rules.pro
  Care_Refrigerator/app/src/androidTest/java/com/example/care_refrigerator/ExampleInstrumentedTest.java
  Care_Refrigerator/app/src/main/AndroidManifest.xml
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/MainActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/OptionActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Care_Refrigerator/app/src/main/res/drawable/ic_launcher_background.xml
  Care_Refrigerator/app/src/main/res/layout/activity_box.xml
  Care_Refrigerator/app/src/main/res/layout/activity_main.xml
  Care_Refrigerator/app/src/main/res/layout/activity_option.xml
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
  Care_Refrigerator/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Care_Refrigerator/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Care_Refrigerator/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Care_Refrigerator/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Care_Refrigerator/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Care_Refrigerator/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Care_Refrigerator/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Care_Refrigerator/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Care_Refrigerator/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Care_Refrigerator/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Care_Refrigerator/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Care_Refrigerator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Care_Refrigerator/app/src/main/res/values/colors.xml
  Care_Refrigerator/app/src/main/res/values/strings.xml
  Care_Refrigerator/app/src/main/res/values/styles.xml
  Care_Refrigerator/app/src/test/java/com/example/care_refrigerator/ExampleUnitTest.java
  Care_Refrigerator/build.gradle
  Care_Refrigerator/gradle.properties
  Care_Refrigerator/gradle/wrapper/gradle-wrapper.jar
  Care_Refrigerator/gradle/wrapper/gradle-wrapper.properties
  Care_Refrigerator/gradlew
  Care_Refrigerator/gradlew.bat
  Care_Refrigerator/settings.gradle
Labels: bug

#2 2020.04.14.
  Care_Refrigerator/.idea/encodings.xml
  Care_Refrigerator/app/src/main/AndroidManifest.xml
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoardActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/MainActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_board.xml
  Care_Refrigerator/app/src/main/res/layout/activity_main.xml
  Care_Refrigerator/app/src/main/res/values/strings.xml
  Care_Refrigerator/app/src/main/res/values/styles.xml
Labels: documentation, good first issue

#3 기본 UI 수정
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoardActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/MainActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/OptionActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_board.xml
  Care_Refrigerator/app/src/main/res/layout/activity_box.xml
  Care_Refrigerator/app/src/main/res/layout/activity_main.xml
  Care_Refrigerator/app/src/main/res/layout/activity_option.xml
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
Labels: 개선(documentation), 추가(enhancement)

#4 냉장고에 물품 넣기
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/MainActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_board.xml
  Care_Refrigerator/app/src/main/res/layout/activity_box.xml
  Care_Refrigerator/app/src/main/res/layout/activity_main.xml
  Care_Refrigerator/app/src/main/res/layout/activity_option.xml
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
  Care_Refrigerator/app/src/main/res/layout/spinner_text_coustom.xml
  Care_Refrigerator/app/src/main/res/values/array.xml
  Care_Refrigerator/app/src/main/res/values/strings.xml
Labels: 개선(documentation), 첫 시도(good first issue), 추가(enhancement)

#6 로그인 및 설정구현, 앱 아이콘 설정
  Care_Refrigerator/.idea/vcs.xml
  Care_Refrigerator/app/build.gradle
  Care_Refrigerator/app/src/main/AndroidManifest.xml
  Care_Refrigerator/app/src/main/ic_launcher_refrigerator-playstore.png
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/OptionActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/loginActivity.java
  Care_Refrigerator/app/src/main/res/drawable/buttonshape.xml
  Care_Refrigerator/app/src/main/res/layout/activity_login.xml
  Care_Refrigerator/app/src/main/res/layout/activity_option.xml
  Care_Refrigerator/app/src/main/res/mipmap-anydpi-v26/ic_launcher_refrigerator.xml
  Care_Refrigerator/app/src/main/res/mipmap-anydpi-v26/ic_launcher_refrigerator_round.xml
  Care_Refrigerator/app/src/main/res/mipmap-hdpi/ic_launcher_refrigerator.png
  Care_Refrigerator/app/src/main/res/mipmap-hdpi/ic_launcher_refrigerator_foreground.png
  Care_Refrigerator/app/src/main/res/mipmap-hdpi/ic_launcher_refrigerator_round.png
  Care_Refrigerator/app/src/main/res/mipmap-mdpi/ic_launcher_refrigerator.png
  Care_Refrigerator/app/src/main/res/mipmap-mdpi/ic_launcher_refrigerator_foreground.png
  Care_Refrigerator/app/src/main/res/mipmap-mdpi/ic_launcher_refrigerator_round.png
  Care_Refrigerator/app/src/main/res/mipmap-xhdpi/ic_launcher_refrigerator.png
  Care_Refrigerator/app/src/main/res/mipmap-xhdpi/ic_launcher_refrigerator_foreground.png
  Care_Refrigerator/app/src/main/res/mipmap-xhdpi/ic_launcher_refrigerator_round.png
  Care_Refrigerator/app/src/main/res/mipmap-xxhdpi/ic_launcher_refrigerator.png
  Care_Refrigerator/app/src/main/res/mipmap-xxhdpi/ic_launcher_refrigerator_foreground.png
  Care_Refrigerator/app/src/main/res/mipmap-xxhdpi/ic_launcher_refrigerator_round.png
  Care_Refrigerator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_refrigerator.png
  Care_Refrigerator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_refrigerator_foreground.png
  Care_Refrigerator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_refrigerator_round.png
  Care_Refrigerator/app/src/main/res/values/ic_launcher_refrigerator_background.xml
  Care_Refrigerator/app/src/main/res/values/strings.xml
  Care_Refrigerator/app/src/main/res/values/styles.xml
Labels: developing, enhancement

#7 정비
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/MainActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_box.xml
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
  Care_Refrigerator/app/src/main/res/values/strings.xml
Labels: developing

#8 리스트뷰에 아이템 추가하기
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_box.xml
  Care_Refrigerator/app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#12 리팩토링
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
Labels: documentation

#13 DB에 아이템 넣기 완료
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
Labels: documentation, enhancement

#14 Login 구현 및 다크모드 구현
  Care_Refrigerator/.idea/dictionaries/USER.xml
  Care_Refrigerator/app/build.gradle
  Care_Refrigerator/app/src/main/AndroidManifest.xml
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/MainActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/OptionActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/loginActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/loginonActivity.java
  Care_Refrigerator/app/src/main/res/drawable/btn.xml
  Care_Refrigerator/app/src/main/res/layout/activity_login.xml
  Care_Refrigerator/app/src/main/res/layout/activity_loginon.xml
  Care_Refrigerator/app/src/main/res/layout/activity_option.xml
  Care_Refrigerator/app/src/main/res/values/colors.xml
  Care_Refrigerator/app/src/main/res/values/strings.xml
  Care_Refrigerator/app/src/main/res/values/styles.xml
Labels: Bug, developing

#16 냉장고 데이터 관리
  Care_Refrigerator/app/src/main/AndroidManifest.xml
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/ObjectData.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/loginActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_box.xml
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
Labels: End, documentation, enhancement

#17 데이터 교환
  Care_Refrigerator/.idea/misc.xml
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_box.xml
Labels: developing, documentation

#18 데이터 로드 완벽 구현
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/BoxActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/MainActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/ObjectData.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/OptionActivity.java
  Care_Refrigerator/app/src/main/java/com/example/care_refrigerator/PushActivity.java
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
  Care_Refrigerator/app/src/main/res/layout/spinner_text_coustom.xml
Labels: End, documentation

#19 디자인 수정작업
  Care_Refrigerator/app/src/main/res/drawable/btn.xml
  Care_Refrigerator/app/src/main/res/drawable/buttonshape.xml
  Care_Refrigerator/app/src/main/res/layout/activity_board.xml
  Care_Refrigerator/app/src/main/res/layout/activity_box.xml
  Care_Refrigerator/app/src/main/res/layout/activity_login.xml
  Care_Refrigerator/app/src/main/res/layout/activity_loginon.xml
  Care_Refrigerator/app/src/main/res/layout/activity_main.xml
  Care_Refrigerator/app/src/main/res/layout/activity_option.xml
  Care_Refrigerator/app/src/main/res/layout/activity_push.xml
  Care_Refrigerator/app/src/main/res/values/strings.xml
Labels: End
